batch_size: 16
id: 42vs6s7p  #pgqicubi
accelerator: gpu
min_epochs: 1
max_epochs: 50
epochs: 10
csv_path: '/content/FOOT40K.csv'
dataset_path: '/content/FOOT40k'
dataset: shoe40k
input_shape: [3, 344, 344]
channels_last: false
criterion: CrossEntropyLoss
project: shoe40k
